# -*- coding: utf-8 -*-
"""project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQfYqLBmubd6B63XL7i80FYXX7W1xlXk
"""

import pandas as pd
from textblob import TextBlob
import matplotlib.pyplot as plt

# Sample social media data
data = {
    'username': ['user1', 'user2', 'user3', 'user4'],
    'post': [
        "I love this product! It's amazing 😍",
        "This is the worst experience I've had.",
        "Meh, it's okay. Nothing special.",
        "Absolutely fantastic! Will buy again."
    ]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Function to get sentiment polarity
def get_sentiment(text):
    blob = TextBlob(text)
    return blob.sentiment.polarity

# Apply sentiment analysis
df['polarity'] = df['post'].apply(get_sentiment)

# Classify as Positive, Negative, or Neutral
def classify_sentiment(score):
    if score > 0:
        return 'Positive'
    elif score < 0:
        return 'Negative'
    else:
        return 'Neutral'

df['sentiment'] = df['polarity'].apply(classify_sentiment)

# Display result
print(df)

# Optional: Visualize
df['sentiment'].value_counts().plot(kind='bar', color=['green', 'red', 'gray'])
plt.title("Sentiment Analysis of Social Media Posts")
plt.ylabel("Number of Posts")
plt.xlabel("Sentiment")
plt.show()